package trust_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/server/api/trust/v1/schema"
	"go.probo.inc/probo/pkg/server/api/trust/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// Logo is the resolver for the logo field.
func (r *organizationResolver) Logo(ctx context.Context, obj *types.Organization) (*types.File, error) {
	scope := coredata.NewScopeFromObjectID(obj.ID)

	organization, err := r.trust.GetOrganization(ctx, scope, obj.ID)
	if err != nil {
		return nil, gqlutils.NotFoundf(ctx, "organization %q not found", obj.ID)
	}

	if organization.LogoFileID == nil {
		return nil, nil
	}

	return r.loadPublicFile(ctx, *organization.LogoFileID)
}

// Organization returns schema.OrganizationResolver implementation.
func (r *Resolver) Organization() schema.OrganizationResolver { return &organizationResolver{r} }

type organizationResolver struct{ *Resolver }
